site:
  # deploy:
  #   s3Url: s3://dinghy-dev-demo-sites-origin
  #   s3Region: eu-west-1
  url: https://cloudfront-site-demo.dinghy.dev
  baseUrl: /showcases-tfl-live-arrivals-by-spectre0100/
  title: by Spectre0100
  navbar:
    title: TfL Live Arrivals
    logo:
      src: /assets/favicon.svg
      # Following config to enable clicking the logo to refresh the page
      href: https://cloudfront-site-demo.dinghy.dev/showcases-tfl-live-arrivals-by-spectre0100/
      target: _self
    items:
      - href: https://github.com/Spectre0100/Spectre0100.github.io
        position: right
        className: header-github-link
        aria-label: GitHub repository
  footer: false
